version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-lima-app
    container_name: web-lima-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - webnet
    command: >
      sh -c "php artisan config:clear &&
             php artisan migrate --force &&
             php-fpm"

  web:
    image: nginx:stable-alpine
    container_name: web-lima-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - webnet

  db:
    image: mysql:8.0
    container_name: web-lima-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: web_lima
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - webnet

volumes:
  dbdata:

networks:
  webnet:
