server {
    listen 80;
    server_name 202.157.185.159 ligamahasiswa.com www.ligamahasiswa.com;

    root /var/www/public;
    index index.php index.html;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

# server {
#     listen 443 ssl;
#     http2 on;
#     server_name 202.157.185.159 ligamahasiswa.com www.ligamahasiswa.com;
#
#     ssl_certificate /etc/nginx/ssl/fullchain.pem;
#     ssl_certificate_key /etc/nginx/ssl/privkey.pem;
#
#     root /var/www/public;
#     index index.php index.html;
#
#     location / {
#         try_files $uri $uri/ /index.php?$query_string;
#     }
#
#     location ~ \.php$ {
#         include fastcgi_params;
#         fastcgi_pass app:9000;
#         fastcgi_index index.php;
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#     }
#
#     location ~ /\.env {
#         deny all;
#     }
# }